Description: Create bation host

Parameters:
  EnvironmentName:
    Description: An environment name of out put that will be used to add prefix for out put of resources after created
    Default: "vpc-secondary-output"
    Type: String

AWSTemplateFormatVersion: "2010-09-09"
Resources:
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          wget http://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
          sudo rpm -Uvh mysql57-community-release-el7-9.noarch.rpm
          sudo rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
          sudo yum install mysql-server -y
          sudo chkconfig mysqld on
          sudo service mysqld restart
      ImageId: ami-0568773882d492fc8
      InstanceType: t2.micro
      KeyName: secondary_udaciy
      BlockDeviceMappings:
          - DeviceName: "/dev/sdk"
            Ebs:
              VolumeSize: '10'
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId:
            Fn::ImportValue:
              !Sub "${EnvironmentName}-PUBLIC-SUBNET-1"
          GroupSet: 
            - Fn::ImportValue:
                !Sub "${EnvironmentName}-APP-SG"
      Tags:
        - Key: Name
          Value: BationHost